# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='T\xedtulo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cria\xe7\xe3o')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publica\xe7\xe3o')),
                ('text', models.TextField(verbose_name='Texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
